# The SDK location is intentionally configurable for CI and local installations.
set(WASI_SDK_PATH "$ENV{WASI_SDK_PATH}" CACHE PATH "WASI SDK root")
if(NOT WASI_SDK_PATH)
  set(WASI_SDK_PATH "/opt/wasi-sdk" CACHE PATH "WASI SDK root" FORCE)
endif()
set(CMAKE_SYSTEM_NAME WASI)
set(CMAKE_SYSTEM_PROCESSOR wasm32)
set(CMAKE_C_COMPILER "${WASI_SDK_PATH}/bin/clang")
set(CMAKE_CXX_COMPILER "${WASI_SDK_PATH}/bin/clang++")
set(CMAKE_SYSROOT "${WASI_SDK_PATH}/share/wasi-sysroot")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_CXX_FLAGS_INIT "--target=wasm32-wasi -msimd128 -fno-exceptions -fno-rtti")
