#include <iostream>
#include <stdexcept>
#include "blindzap/verifier.h"
#include "blindzap/bitcoin_core.h"
namespace proofs { namespace {
void Require(bool ok, const char* text) { if (!ok) throw std::runtime_error(text); }
BlindzapEnvelopeV1 Envelope() { BlindzapEnvelopeV1 e; e.statement.network = BlindzapNetwork::kRegtest; e.statement.verifier="v"; e.statement.purpose="p"; e.statement.not_before=1; e.statement.expires_at=9; BlindzapClaimV1 c; c.amount_sats=7; c.program[0]=3; e.statement.claims={c}; e.proof.bytes={1}; return e; }
class Fake final : public BlindzapChainProvider { public: BlindzapProviderKind kind() const override { return historical ? BlindzapProviderKind::kHistoricalSnapshot : BlindzapProviderKind::kCurrentTip; } BlindzapChainEvidence Lookup(const BlindzapChainRequest&) override { ++calls; return evidence; } bool historical=false; int calls=0; BlindzapChainEvidence evidence; };
BlindzapVerifierConfig Config(Fake* fake) { BlindzapVerifierConfig c; c.policy.now=2; c.policy.verifier="v"; c.policy.purpose="p"; c.policy.consume_nonce=[](const std::array<uint8_t,32>&){return true;}; c.verify_proof=[](const BlindzapEnvelopeV1&){return true;}; c.provider=fake; return c; }
void TestStates() { auto e=Envelope(); std::vector<uint8_t> wire; Require(EncodeBlindzapEnvelope(e,&wire),"encode"); Fake f; f.evidence.status=BlindzapChainStatus::kUnspent; f.evidence.network=e.statement.network; f.evidence.amount_sats=7; f.evidence.script_pub_key={0,20}; f.evidence.script_pub_key.insert(f.evidence.script_pub_key.end(),e.statement.claims[0].program.begin(),e.statement.claims[0].program.end()); auto c=Config(&f); Require(VerifyBlindzap(wire,c).result==BlindzapVerifyResult::kValidCurrent,"current"); e.statement.has_snapshot=true; f.historical=true; Require(EncodeBlindzapEnvelope(e,&wire),"snapshot encode"); Require(VerifyBlindzap(wire,Config(&f)).result==BlindzapVerifyResult::kValidHistorical,"historical"); f.historical=false; Require(VerifyBlindzap(wire,Config(&f)).result==BlindzapVerifyResult::kStateInconclusive,"unsupported history"); e.statement.has_snapshot=false; Require(EncodeBlindzapEnvelope(e,&wire),"current encode"); f.evidence.amount_sats=8; Require(VerifyBlindzap(wire,Config(&f)).result==BlindzapVerifyResult::kStateInconclusive,"amount mismatch"); f.evidence.amount_sats=7; f.evidence.status=BlindzapChainStatus::kSpent; Require(VerifyBlindzap(wire,Config(&f)).result==BlindzapVerifyResult::kSpentAtSnapshot,"spent"); f.evidence.status=BlindzapChainStatus::kUnspent; f.evidence.confirmations=0; c=Config(&f); c.min_confirmations=1; Require(VerifyBlindzap(wire,c).result==BlindzapVerifyResult::kStaleSnapshot,"stale"); c=Config(&f); c.supports=[](const BlindzapEnvelopeV1&){return false;}; Require(VerifyBlindzap(wire,c).result==BlindzapVerifyResult::kUnsupported,"unsupported"); c=Config(&f); c.verify_proof=[](const BlindzapEnvelopeV1&){return false;}; const int before=f.calls; Require(VerifyBlindzap(wire,c).result==BlindzapVerifyResult::kInvalidProof && f.calls==before,"invalid proof queried chain"); Require(VerifyBlindzap({0},Config(&f)).result==BlindzapVerifyResult::kMalformedStatement,"malformed"); }
void TestAggregateAndBridge() { auto e=Envelope(); BlindzapClaimV1 another=e.statement.claims[0]; another.txid[0]=1; e.statement.claims.push_back(another); std::vector<uint8_t> wire; Require(EncodeBlindzapEnvelope(e,&wire),"multi encode"); Fake f; f.evidence.status=BlindzapChainStatus::kUnspent; f.evidence.network=e.statement.network; f.evidence.amount_sats=7; f.evidence.script_pub_key={0,20}; f.evidence.script_pub_key.insert(f.evidence.script_pub_key.end(),e.statement.claims[0].program.begin(),e.statement.claims[0].program.end()); auto c=Config(&f); int calls=0; c.minimum_total_sats=15; Require(VerifyBlindzap(wire,c).result==BlindzapVerifyResult::kStateInconclusive,"threshold accepted"); c.minimum_total_sats=14; Require(VerifyBlindzap(wire,c).result==BlindzapVerifyResult::kValidCurrent,"aggregate total"); e.statement.has_bridge_binding=true; e.statement.bridge.asset_id="asset"; e.statement.bridge.destination_commitment[0]=1; e.statement.bridge.lock_id[0]=2; Require(EncodeBlindzapEnvelope(e,&wire),"bridge encode"); c=Config(&f); Require(VerifyBlindzap(wire,c).result==BlindzapVerifyResult::kBridgeRejected,"missing bridge lock accepted"); c.bridge_authorized=[&](const BlindzapStatementV1&){return ++calls==1;}; Require(VerifyBlindzap(wire,c).result==BlindzapVerifyResult::kValidCurrent,"bridge callback rejected"); Require(VerifyBlindzap(wire,c).result==BlindzapVerifyResult::kBridgeRejected,"bridge replay callback accepted"); }
void TestResultContract() { const BlindzapVerifyResult values[] = {BlindzapVerifyResult::kInvalidProof, BlindzapVerifyResult::kMalformedStatement, BlindzapVerifyResult::kUnsupported, BlindzapVerifyResult::kStateInconclusive, BlindzapVerifyResult::kSpentAtSnapshot, BlindzapVerifyResult::kStaleSnapshot, BlindzapVerifyResult::kBridgeRejected, BlindzapVerifyResult::kValidHistorical, BlindzapVerifyResult::kValidCurrent}; for (size_t i=0;i<sizeof(values)/sizeof(values[0]);++i) for(size_t j=i+1;j<sizeof(values)/sizeof(values[0]);++j) { Require(std::string(BlindzapVerifyResultName(values[i])) != BlindzapVerifyResultName(values[j]),"unique JSON result"); Require(BlindzapVerifyExitCode(values[i]) != BlindzapVerifyExitCode(values[j]) || (BlindzapVerifyExitCode(values[i]) == 0 && (values[i] == BlindzapVerifyResult::kValidCurrent || values[i] == BlindzapVerifyResult::kValidHistorical)),"stable exit code"); } }
void TestCoreAdapter() { int calls=0; BitcoinCoreCurrentTipProvider p("bitcoin-cli",BlindzapNetwork::kRegtest,[&](const std::vector<std::string>& argv){ ++calls; if(argv[1]=="getblockchaininfo") return BlindzapProcessResult{0,"{\"chain\":\"regtest\",\"blocks\":1}",""}; return BlindzapProcessResult{0,"{\"valueSat\":7,\"confirmations\":2,\"hex\":\"00140300000000000000000000000000000000000000\"}",""}; }); BlindzapChainRequest r; r.network=BlindzapNetwork::kRegtest; auto e=p.Lookup(r); Require(e.status==BlindzapChainStatus::kUnspent && e.amount_sats==7 && calls==3,"core stable tip adapter"); }
} }
int main() { try { proofs::TestStates(); proofs::TestAggregateAndBridge(); proofs::TestResultContract(); proofs::TestCoreAdapter(); } catch(const std::exception& e) { std::cerr << "not ok - " << e.what() << '\n'; return 1; } std::cout << "BlindZap integration tests passed\n"; }
